<?php
session_start();
if($_SESSION['acesso']==""){
  header("Location:index.php");
}
  if(isset($_SESSION['ifon'])){
    echo $_SESSION['ifon'];
    unset ($_SESSION['ifon']);

  }
if(isset($_COOKIE["tema"])){
  $tema = $_COOKIE["tema"];
}else{
  setcookie("tema","a", (time() + (500 * 24 * 3600)));
}
?>
<!Doctype html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cores de etiqueta</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" type="text/css" href="css/es.css">
  <?php
  if($_COOKIE["tema"] <> "a"){
    echo "<link rel='stylesheet' type='text/css' href='css/$tema.css'>";
  }

  ?>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    var cores = [
      '1.60.16.01 --> Especialização em Saúde da Família : Branco',
      '1.64.04.01 --> Mestrado em Psicologia : ',
      'AC01 --> Acordo Cultural : Azul',
      'AT01 --> Alunos Em Trânsito : Branco',
      'AU01 --> LIC EM CIÊNCIAS AGRARIAS - AUTAZES : ',
      'AV01 --> Alunos Avulsos : Verde',
      'BA01 --> LICENC. CIÊNCIAS BIOLÓGICAS - BARCELOS : ',
      'BB01 --> ADMINISTRACAO - BORBA : ',
      'BB02 --> ADMINISTRACAO - BORBA : ',
      'BC01 --> LETRAS - LINGUA PORTUGUESA : ',
      'BC02 --> FILOSOFIA - B CONSTANT : ',
      'BC03 --> MATEMATICA - B CONSTANT : ',
      'CH01 --> Complemento de Habilitação : Amarelo',
      'CO01 --> Letras - Coari : ',
      'CO02 --> Pedagogia - Coari : ',
      'CO03 --> Ed. Fisica Lic.Curta : ',
      'CO04 --> Lic. Filosofia - Coari : ',
      'CO05 --> Geografia - Coari : ',
      'CO06 --> Administraçao - Coari : ',
      'CO07 --> Serviço Social - Coari : ',
      'DI01 --> Disciplinas Isoladas : Azul',
      'EM01 --> Enfermagem : Rosa',
      'EN01 --> Lic. Ciencias Agrarias - Envira : ',
      'ES01 --> Alunos Especiais : Amarelo',
      'ET01 --> Pedagogia Magist. 1 a 4a. Séries : ',
      'FA01 --> Administração : Azul',
      'FA01 AED --> Administraçao de empresas : Azul',
      'FA01 APD --> Administraçao publica : Azul',
      'FA02 --> Administração : Rosa',
      'FA02 AEN --> Administraçao de empresas : Rosa',
      'FA02 APN --> Administraçao publica : Rosa',
      'FA03 --> Ciências Contábeis Diurno : Branco',
      'FA04 --> Ciências Contábeis Noturno : Verde',
      'FA05 --> Ciências Econômicas Diurno : Rosa',
      'FA06 --> Ciencias Economicas Noturno : Amarelo',
      'FA07 --> Administração Noturno Plen. ECT : ',
      'FA08 --> Administração Plenificação : Azul',
      'FA09 --> Administração Pública Municipal : Branco',
      'FA10 --> Administração Pública Municipal : Verde',
      'FA11 --> Administração Complementação de Estudos : Amarelo',
      'FA12 --> Administração Pública - Complementação de Estudos : Azul',
      'FA13 --> Administração Pública - Complementação de Estudos : Rosa',
      'FA20 --> Administração Urucurituba : Rosa',
      'FA30 --> Administração Universitária : Azul',
      'FA50 --> Administração EAD Coari : Branco',
      'FA51 --> Administração EAD Lábrea : Verde',
      'FA52 --> Administração EAD Manacapuru : Rosa',
      'FA53 --> Administração EAD Maués : Amarelo',
      'FA54 --> Administração Pública EAD Coari : Azul',
      'FA55 --> Administração Pública EAD Itacoatiara : Branco',
      'FA56 --> Administração Pública EAD Lábrea : Rosa',
      'FA57 --> Administração Pública EAD Manacapuru : Amarelo',
      'FA58 --> Administração Pública EAD Manaus : Azul',
      'FA59 --> Administração Pública EAD Maués : Rosa',
      'FA60 --> Administração - EAD - Sta Isabel R Negro : Verde',
      'FA61 --> Administração - EAD - BOA VISTA/RR : Rosa',
      'FA62 --> Administração EAD Caracarai/RR : Amarelo',
      'FA63 --> Administração Pública - EAD - ACRELÂNDIA/AC : Azul',
      'FA64 --> Administração Pública - EAD - BRASILEIA/AC : Rosa',
      'FA65 --> Administração Pública - EAD - TARAUACÁ/AC : Verde',
      'FA66 --> Administração Pública - EAD - CRUZEIRO DO SUL/AC : Rosa',
      'FA67 --> Administração Pública - EAD - MANAUS : Amarelo',
      'FA68 --> Administração Pública - EAD - TEFÉ : Azul',
      'FD01 --> Direito  : Azul',
      'FD02 --> Direito  : Branco',
      'FE01 --> Pedagogia : Rosa',
      'FE02 --> Pedagogia : Verde',
      'FE02-CHAE --> Pedagogia Administração Escolar : Verde',
      'FE02-CHAIE --> Pedagogia Adiministração Escolar e Inspeção Escolar no Ensino Básico : Verde',
      'FE02CHIE --> Pedagogia Inspeção Escolar : Verde',
      'FE02CHOE --> Pedagogia Orientação Educacional : Verde',
      'FE02-CHSE --> Pedagogia Supervisao Escolar : ',
      'FE02-CHSEO --> Pedagogia Supervisão Escolar e Orientação Educacional : Amarelo',
      'FE03 --> Pedagogia : Amarelo',
      'FE03-CHAE --> Pedagogia Administração Escolar : Amarelo',
      'FE03-CHAIE --> Pedagogia Administração Escolar e Inpeção Escolar no Ensino Básico : Amarelo',
      'FE03-CHIE -->  : Amarelo',
      'FE03-CHOE --> Pedagogia Orientação Educacional : Amarelo',
      'FE03CHSE --> Pedagogia Supervisão Escolar : Amarelo',
      'FE03-CHSE  --> Pedagogia Supervisão Escolar : Amarelo',
      'FE03-CHSEO --> Pedagogia Supervisão Escolar e Orientação Educacional : Amarelo',
      'FE06 --> Psicologia : Rosa',
      'FE06B --> Psicologia Bacharelado : Rosa',
      'FE06-CHB --> Psicologia CH Bacharelado : Rosa',
      'FE06-CHFP --> Psicologia CH Formação do Psicólogo : Rosa',
      'FE06-CHL --> Psicologia CH Licenciatura : Rosa',
      'FE06-FP --> Psicologia Formação do Psicólogo : Rosa',
      'FE06-L --> Psicologia Licenciatura : Rosa',
      'FE07 --> Formação de Professores Indígenas - Humanas e Sociais - Borba : Amarelo',
      'FE08 --> Formação de Professores Indígenas - Letras e Artes - Borba : Verde',
      'FE09 --> Formação de Professores Indígenas - Exatas e Biológicas - Borba : Azul',
      'FE10 --> Formação de Professores Indígenas - Humanas e Sociais - Maués : Branco',
      'FE11 --> Formação de Professores Indígenas - Letras e Artes - Maués : Rosa',
      'FE12 --> Formação de Professores Indígenas - Exatas e Biológicas - Maués : Amarelo',
      'FE13 --> Formação de Professores Indígenas - Humanas e Sociais - M. Solimões : Verde',
      'FE14 --> Formação de Professores Indígenas - Letras e Artes - M. Solimões : Azul',
      'FE15 --> Formação de Professores Indígenas - Exatas e Biológicas - M. Solimões : Branco',
      'FE16 --> Formação de Professores Indígenas - Letras e Artes - Alto Rio Negro : Azul',
      'FE17 --> Formação de Professores Indígenas - Letras e Artes - Alto Solimões : Verde',
      'FE22 --> Formação de Professores Indígenas - Humanas e Sociais - Lábrea : Amarelo',
      'FE25 --> Formação de Professores Indígenas - Humanas e Sociais - Manicoré : Branco',
      'FG01 --> Agronomia : Branco',
      'FG02 --> Engenharia Florestal : Verde',
      'FG03 --> Engenharia de Pesca : Rosa',
      'FG04 --> Zootecnia : Amarelo',
      'FG05 --> Engenharia de Alimentos : Verde',
      'FG50 --> Licenciatura em Ciências Agrárias EAD Coari : Azul',
      'FG51 --> Licenciatura em Ciências Agrárias EAD Lábrea : Branco',
      'FG52 --> Licenciatura em Ciências Agrárias EAD Manacapuru : Verde',
      'FG53 --> Licenciatura em Ciências Agrárias EAD Maués : Rosa',
      'FG54 --> Licenciatura em Ciências Agrárias EAD Manaquiri : Amarelo',
      'FG55 --> Licenciatura em Ciências Agrárias EAD Santa Isabel do Rio Negro : Azul',
      'FG56 --> Licenciatura em Ciências Agrárias EAD Tefé : Branco',
      'FG57 --> Licenciatura em Ciencias Agrarias EAD Caroebe RR : Verde',
      'FG58 --> Licenciatura em Ciências Agrárias - EAD - BONFIM/RR : Rosa',
      'FG59 --> Licenciatura em Ciências Agrárias - EAD - IRACEMA/RR : Amarelo',
      'FG60 --> Licenciatura em Ciências Agrárias - EAD - SANTA IZABEL DO RIO NEGRO : Rosa',
      'FG61 --> Licenciatura em Ciências Agrárias - EAD - LÁBREA : Azul',
      'FG62 --> Licenciatura em Ciências Agrárias - EAD - COARI : Branco',
      'FG63 --> Licenciatura em Ciências Agrárias - EAD - MANACAPURU : Verde',
      'FG64 --> Licenciatura em Ciências Agrárias - EAD - MAUÉS : Rosa',
      'FG65 --> Licenciatura em Ciências Agrárias - EAD - AMAJARI/RR : Amarelo',
      'FG66 --> Licenciatura em Ciências Agrárias - EAD - CARACARAI/RR : Azul',
      'FG67 --> Licenciatura em Ciências Agrárias - EAD - BOA VISTA/RR : Branco',
      'FS01 --> Farmácia : Amarelo',
      'FS01-CHAC --> Farmácia Análises Clínicas : Amarelo',
      'FS01-CHBA --> Farmácia Bioquímica dos Alimentos : Amarelo',
      'FS02 --> Medicina : Verde',
      'FS03 --> Odontologia : Rosa',
      'FT01 --> Engenharia Civil : Amarelo',
      'FT02 --> Engenharia Elétrica : Azul',
      'FT02-E --> Engenharia Elétrica Eletrônica : Azul',
      'FT02-ET --> Engenharia Elétrica Eletrotécnica : Azul',
      'FT02-T --> Engenharia Elétrica Telecomunicações : Azul',
      'FT03 --> Engenharia Mecânica : ',
      'FT04 --> Desenho Industrial : Amarelo',
      'FT04-PP --> Desenho Industrial Projeto do Produto : Amarelo',
      'FT04-PV --> Desenho Industrial Programação Visual : Amarelo',
      'FT05 --> Engenharia da Computação : Verde',
      'FT06 --> Engenharia de Produção : Rosa',
      'FT07 --> Design : Amarelo',
      'FT08 --> Engenharia de Materiais : Azul',
      'FT09 --> Engenharia Mecânica : Branco',
      'FT10 --> Arquitetura : Verde',
      'FT11 --> Engenharia de Gás e Petróleo : Rosa',
      'FT12 --> Engenharia Química : Amarelo',
      'HB01 --> FE06 Lic. Psicologia : ',
      'HB03 --> Complemento de Habilitação - Licenciatura em Física : Azul',
      'HB04 --> IE04 Bach. Fisica : ',
      'HB06 --> IH07 Bach. Geografia : ',
      'HB07 --> IE03 Lic. Matematica : ',
      'HB08 --> IE03 Bach. Matematica : ',
      'HB09 --> IH05 Lic. Filosofia : ',
      'HB12 --> Complemento de Habilitação - Licenciatura em Ciências : Branco',
      'HB13 --> FS01 Farmacia Bioquimica dos Alimentos : ',
      'HB14 --> Complemento de Habilitação - Farmácia Análises Clínicas : Verde',
      'HB15 --> IE05 Lic. Quimica : ',
      'HB18 --> Administraçao Escolar e Inspeção Escolar no Ensino Basico Matutito : ',
      'HB19 --> Complemento de Habilitação - Supervisão Escolar e Orientação Educacional - Matutino : Rosa',
      'HB20 --> Complemento de Habilitação - Supervisão Escolar e Orientação Educacional - Vespertino : Amarelo',
      'HB21 --> Administraçao Escolar e Inspeção Escolar no Ensino Basico Vespertino : ',
      'HB23 --> IB01 Bach. Ciencias : ',
      'HU01 --> Letras - Humaita : ',
      'HU02 --> Matematica - Humaita : ',
      'HU03 --> Lic. Ciencias Agrarias - Humaita : ',
      'IA01 --> Agronomia - Humaitá : Branco',
      'IA02 --> Engenharia Ambiental - Humaitá : Verde',
      'IA03 --> Ciências - Biologia e Química : Rosa',
      'IA04 --> Pedagogia : Amarelo',
      'IA05 --> Letras - Língua Portuguesa e Língua Inglesa : Azul',
      'IA06 --> Ciências - Matemática e Física : Branco',
      'IB01 --> Ciências Biológicas : Branco',
      'IB01-B --> Ciências Biológicas Bacharelado : Branco',
      'IB01-BBC --> Ciências Biológicas Biodiversidade e Conservação : Branco',
      'IB01-BGB --> Ciências Biológicas Genética e Biotecnologia : Branco',
      'IB01-CHBBC --> Ciências Biológicas CH Biodiversidade e Conservação : Branco',
      'IB01-CHBGB --> Ciências Biológicas CH Genética e Biotecnologia : Branco',
      'IB01-L --> Ciências Biológicas Licenciatura : Branco',
      'IB02 --> Educação Física : Rosa',
      'IB03 --> Ciências : Amarelo',
      'IB04 --> Educaçao Fisica Feminino : ',
      'IB05 --> Ciências Naturais : Azul',
      'IB06 --> Educação Física Promoção em Saúde e Lazer : Branco',
      'IB07 --> Educação Física Treinamento Esportivo : Verde',
      'IB08 --> Fisioterapia : Rosa',
      'IB09 --> Biotecnologia : Amarelo',
      'IB10 --> Licenciatura em Ciências Biológicas EAD Manaus : Azul',
      'IB11 --> Licenciatura em Ciências Biológicas EAD Itacoatiara : Branco',
      'IB12 --> Licenciatura em Ciências Biológicas EAD Coari : Verde',
      'IB13 --> Licenciatura em Ciências Biológicas EAD Parintins : Rosa',
      'IB14 --> Ciências Naturais : Amarelo',
      'IB15 --> Ciências Biológicas : Azul',
      'IB16 --> Educação Física : Branco',
      'IB30 --> Licenciatura em Ciências Biológicas EAD Benjamim Constant : Azul',
      'IB31 --> Licenciatura em Ciências Biológicas EAD Humaitá : Branco',
      'IB32 --> Licenciatura em Ciências Biológicas EAD São Gabriel da Cachoeira : Verde',
      'IB33 --> Licenciatura em Ciências Biológicas - EAD - CARACARAI/RR : Rosa',
      'IB34 --> Licenciatura em Ciências Biológicas - EAD - MUCAJAI/RR : Amarelo',
      'IB35 --> Licenciatura em Ciências Biológicas - EAD - SÃO LUIZ DO ANAUA/RR : Azul',
      'IB50 --> Licenciatura em Educação Física EAD Autazes : Rosa',
      'IB51 --> Licenciatura em Educação Física EAD Barcelos : Amarelo',
      'IB52 --> Licenciatura em Educação Física EAD Benjamin Constant : Azul',
      'IB53 --> Licenciatura em Educação Física EAD Borba : Branco',
      'IB54 --> Licenciatura em Educação Física EAD Carauari : Verde',
      'IB55 --> Licenciatura em Educação Física EAD Coari : Rosa',
      'IB56 --> Licenciatura em Educação Física EAD Eirunepé : Amarelo',
      'IB57 --> Licenciatura em Educação Física EAD Fonte Boa : Azul',
      'IB58 --> Licenciatura em Educação Física EAD Guajará : Branco',
      'IB59 --> Licenciatura em Educação Física EAD Humaitá : Verde',
      'IB60 --> Licenciatura em Educação Física EAD Itacoatiara : Rosa',
      'IB61 --> Licenciatura em Educação Física EAD Lábrea : Amarelo',
      'IB62 --> Licenciatura em Educação Física EAD Manacapuru : Azul',
      'IB63 --> Licenciatura em Educação Física EAD Manaus : Branco',
      'IB64 --> Licenciatura em Educação Física EAD Maués : Verde',
      'IB65 --> Licenciatura em Educação Física EAD Parintins : Rosa',
      'IB66 --> Licenciatura em Educação Física EAD São Gabriel da Cachoeira : Amarelo',
      'IB67 --> Licenciatura em Educação Física EAD Tefé : Azul',
      'IB68 --> Licenciatura em Educação Física - EAD - SANTA ISABEL DO RIO NEGRO : Branco',
      'IB69 --> Licenciatura em Educação Física - EAD - BOA VISTA/RR : Verde',
      'IB70 --> Licenciatura em Educação Física - EAD - ITACOATIARA : Rosa',
      'IB71 --> Licenciatura em Educação Física - EAD - LABREA : Amarelo',
      'IB72 --> Licenciatura em Educação Física - EAD - MAUÉS : Azul',
      'IB73 --> Licenciatura em Educação Física - EAD - MANACAPURU : Branco',
      'IE01 --> Estatística : Branco',
      'IE02 --> Geologia : Verde',
      'IE03 --> Matemática : Rosa',
      'IE03-B --> Matemática Bacharelado : Rosa',
      'IE03-CHB --> Matemática CH Bacharelado : Rosa',
      'IE03-CHL --> Matemática CH Licenciatura : Rosa',
      'IE03-L --> Matemática Licenciatura : Rosa',
      'IE04 --> Física : Amarelo',
      'IE04-B --> Física Bacharelado : Amarelo',
      'IE04-CHB --> Física CH Bacharelado : Amarelo',
      'IE04-CHL --> Física CH Licenciatura : Amarelo',
      'IE04-L --> Física Licenciatura : Amarelo',
      'IE05 --> Química : Azul',
      'IE05-B --> Química Bacharelado : Azul',
      'IE05-CHB --> Química CH Bacharelado : Azul',
      'IE05-CHL --> Química CH Licenciatura : Azul',
      'IE05-L --> Química Licenciatura : Azul',
      'IE06 --> Processamento de Dados : Rosa',
      'IE07 --> Matemática Licenciatura : Amarelo',
      'IE08 --> Ciência da Computação : Azul',
      'IE09 --> Química Licenciatura : Branco',
      'IE10 --> Física Licenciatura : Verde',
      'IE11 --> Química Bacharelado : Rosa',
      'IE12 --> Química Licenciatura : Amarelo',
      'IE13 --> Física Licenciatura : Azul',
      'IE14 --> Física Bacharelado : Branco',
      'IE15 --> Sistemas de Informação : Verde',
      'IE16 --> Matemática Aplicada : Amarelo',
      'IE17 --> Engenharia de Software : Azul',
      'IH01 --> Biblioteconomia : Rosa',
      'IH02 --> Comunicaçao Social : ',
      'IH03 --> Letras : Amarelo',
      'IH03-F --> Letras Língua e Literatura Francesa : Amarelo',
      'IH03-I --> Letras Língua e Literatura Inglesa : Amarelo',
      'IH03-P --> Letras Língua e Literatura Portuguesa : Amarelo',
      'IH04 --> Estudos Sociais : ',
      'IH05 --> Filosofia : ',
      'IH06 --> Serviço Social : Rosa',
      'IH07 --> Geografia : Amarelo',
      'IH07-B --> Geografia Bacharelado : Amarelo',
      'IH07-CHB --> Geografia CH Bacharelado : Amarelo',
      'IH07-CHL --> Geografia CH Licenciatura : Amarelo',
      'IH07-L --> Geografia Licenciatura : Amarelo',
      'IH08 --> História : Verde',
      'IH08 - CHL --> História CH Licenciatura : Verde',
      'IH08-B --> História Bacharelado : Verde',
      'IH08-CHB --> História CH Bacharelado : Verde',
      'IH08-CHL --> Historia CH Licenciatura : ',
      'IH08-L --> História Licenciatura : Verde',
      'IH09 --> Educação Artística : Azul',
      'IH09-D --> Educação Artística Desenho : Azul',
      'IH09-M --> Educação Artística Música : Azul',
      'IH10 --> Ciências Sociais Bacharelado : Branco',
      'IH10-CHL --> Ciências Sociais CH Licenciatura : Branco',
      'IH11 --> Comunicação Social Jornalismo : Rosa',
      'IH12 --> Comunicação Social Relações Públicas : Amarelo',
      'IH13 --> Letras Língua e Literatura Portuguesa : Verde',
      'IH14 --> Filosofia : Azul',
      'IH14-B --> Filosofia Bacharelado : Azul',
      'IH14-CHB --> Filosofia CH Bacharelado : Azul',
      'IH14-CHL --> Filosofia CH Licenciatura : Azul',
      'IH14-L --> Filosofia Licenciatura : Azul',
      'IH15 --> Letras Língua e Literatura Inglesa : Branco',
      'IH16 --> Letras Língua e Literatura Francesa : Rosa',
      'IH17 --> Lic. Geografia Plenific Seduc : Amarelo',
      'IH18 --> Artes Plásticas Licenciatura : Azul',
      'IH19 --> Música Licenciatura : Branco',
      'IH20 --> História : Verde',
      'IH21 --> Letras Língua e Literatura Espanhola : Rosa',
      'IH22 --> Geografia Licenciatura : Amarelo',
      'IH23 --> Letras Língua e Literatura Portuguesa : Azul',
      'IH24 --> Artes Plásticas : Branco',
      'IH25 --> Arquivologia : Verde',
      'IH26 --> Serviço Social : Rosa',
      'IH27 --> Jornalismo : Amarelo',
      'IH28 --> Música   : Azul',
      'IH29 --> Letras Língua e Literatura Japonesa : Rosa',
      'IH30 --> Artes Visuais : Branco',
      'IH31 --> Artes Visuais : Verde',
      'IH32 --> Letras - Libras : Rosa',
      'IH33 --> Licenciatura Indígena Políticas Educacionais e Desenvolvimento Sustenável Baniwa 1° Licenciatura : Amarelo',
      'IH34 --> Licenciatura Indígena Políticas Educacionais e Desenvolvimento Sustenável Tukano 1° Licenciatura : Azul',
      'IH35 --> Licenciatura Indígena Políticas Educacionais e Desenvolvimento Sustenável Nheengatu 1° Licenciatura : Rosa',
      'IH36 --> Licenciatura Indígena Políticas Educacionais e Desenvolvimento Sustentável - Yanomami : Verde',
      'IH37 --> Licenciatura Indígena Políticas Educacionais e Desenvolvimento Sustentável - Sateré-Mawé : Amarelo',
      'IH38 --> Licenciatura Indígena Políticas Educacionais e Desenvolvimento Sustentável - Nheengatu : Azul',
      'IH50 --> Licenciatura em Artes Plásticas EAD Coari : Branco',
      'IH51 --> Licenciatura em Artes Plásticas EAD Lábrea : Verde',
      'IH52 --> Licenciatura em Artes Plásticas EAD Manacapuru : Rosa',
      'IH53 --> Licenciatura em Artes Plásticas EAD Maués : Amarelo',
      'IH54 --> Licenciatura em Artes Plásticas EAD Manaquiri : Azul',
      'IH55 --> Licenciatura em Artes Plásticas EAD Santa Isabel do Rio Negro : Rosa',
      'IH56 --> Licenciatura em Artes Plásticas EAD Tefé : Branco',
      'IH57 --> Licenciatura em Artes Visuais - EAD - ITACOATIARA : Papel Reciclado',
      'IH58 --> Licenciatura em Artes Visuais - EAD - SANTA ISABEL DO RIO NEGRO : Rosa',
      'IH59 --> Licenciatura em Artes Visuais - EAD - TEFÉ : Amarelo',
      'IH61 --> Licenciatura Indígena Políticas Educacionais e Desenvolvimento Sustenável Tukano 1° Licenciatura : Rosa',
      'IN01 --> Administração - Benjamin Constant : Branco',
      'IN02 --> Pedagogia - Benjamin Constant : Verde',
      'IN03 --> Antropologia - Benjamin Constant : Rosa',
      'IN04 --> Ciências Agrárias e do Ambiente - Benjamin Constant : Amarelo',
      'IN05 --> Letras Portugues e Espanhol - Benjamin Constant : Azul',
      'IN06 --> Ciências - Biologia e Química - Benjamin Constant : Branco',
      'IN07 --> Ciências Agrárias e do Ambiente - Benjamin Constant : Verde',
      'IP01 --> Administração : Branco',
      'IP02 --> Comunicação Social - Jornalismo : Verde',
      'IP03 --> Educação Fisica : Rosa',
      'IP04 --> Pedagogia : Amarelo',
      'IP05 --> Serviço Social : Azul',
      'IP06 --> Zootecnia : Branco',
      'IP07 --> Artes Visuais : Verde',
      'IS01 --> Nutrição : Branco',
      'IS02 --> Biotecnologia : Verde',
      'IS03 --> Fisioterapia : Rosa',
      'IS04 --> Enfermagem : Amarelo',
      'IS05 --> Ciencias - Matematica e Fisica : Azul',
      'IS06 --> Ciencias - Biologia e Quimica : Branco',
      'IS07 --> Medicina : Recicl',
      'IT01 --> Sistemas de Informação : Branco',
      'IT01 --> Pedagogia - Supervisão Escolar : ',
      'IT02 --> Farmácia : Verde',
      'IT02 --> Educação Fisica : ',
      'IT03 --> Engenharia de Produção : Rosa',
      'IT03 --> Pedagogia - Itacoatiara : ',
      'IT04 --> Ciencias - Matematica e Fisica : Amarelo',
      'IT04 --> Letras - Itacoatiara : ',
      'IT05 --> Ciencias - Quimica e Biologia : Azul',
      'IT05 --> Administração Contínuo : ',
      'IT06 --> Quimica Industrial : Branco',
      'IT06 --> Pedagogia - Itacoatiara : ',
      'IT07 -->  : Verde',
      'IT07 --> Ciencias Biologicas - Itacoatiara : ',
      'IT08 -->  : Rosa',
      'IT08 --> Matematica - Itacoatiara : ',
      'IT09 -->  : Amarelo',
      'IT09 --> Letras - Lingua Portuguesa - Itacoatiara : ',
      'IT10 -->  : Azul',
      'IT10 --> Administração - Itacoatiara : ',
      'IT11 -->  : Branco',
      'IT11 --> Administração - Itacoatiara : ',
      'IT12 -->  : Verde',
      'IT13 -->  : Rosa',
      'IT14 -->  : Amarelo',
      'IT15 -->  : Azul',
      'IT16 --> Engenharia de Software : Branco',
      'IT17 --> Engenharia Sanitária : Verde',
      'IT18 --> Agronomia : Rosa',
      'MA03 --> Lic. Educaçao Fisica : ',
      'MC01 --> Ciencias Manicore Fora de Sede : ',
      'MC02 --> Lic. Ciencias Agrarias Manicore : ',
      'MC03 --> Lic. Matematica - Manicore : ',
      'ME01 --> Educaçao Fisica Lic. Curta : ',
      'MN01 --> Letras Lingua Portuguesa : ',
      'PA01 --> Geografia Licenciatura Parintins : Verde',
      'PA02 --> Fisica - Parintins : Rosa',
      'PA03 --> Matematica Licenciatura : Amarelo',
      'PA04 --> Quimica - Parintins : Azul',
      'PA06 --> Filosofia Parintins : ',
      'PA07 -->  : Branco',
      'PA08 --> Pedagogia Parintins  : ',
      'PA09 -->  : Verde',
      'PA10 -->  : Rosa',
      'PA100 --> Ciências Biológicas Itacoatiara 2° Licenciatura : Branco',
      'PA101 --> Ciências Biológicas Eirunepé 2° Licenciatura : Amarelo',
      'PA102 --> Ciências Biológicas São Gabriel da Cachoeira 2° Licenciatura : Verde',
      'PA103 --> Ciências Biológicas Coari 2° Licenciatura : Rosa',
      'PA104 --> Ciências Naturais Benjamin Constant 2° Licenciatura : Amarelo',
      'PA105 --> Educação Física São Gabriel da Cachoeira 1° Licenciatura : Branco',
      'PA106 --> Educação Física Jutaí 2° Licenciatura : Verde',
      'PA107 --> Ciências Naturais São Gabriel da Cachoeira 2° Licenciatura : Azul',
      'PA108 --> Ciências Naturais Eirunepé 2° Licenciatura : Branco',
      'PA109 --> Educação Física - Boa Vista do Ramos 1ªLic : Rosa',
      'PA110 --> Ciências Naturais Coari 2° Licenciatura : Verde',
      'PA111 --> Educação Física Envira 1° Licenciatura : Rosa',
      'PA112 --> Educação Física Itacoatira 1° Licenciatura : Branco',
      'PA113 --> Ciências Biológicas Fonte Boa 1° Licenciatura : Amarelo',
      'PA114 --> Educação Física - Codajás 1ªLic : Verde',
      'PA115 --> Educação Física Itacoatira 1° Licenciatura : Azul',
      'PA116 --> Ciências Naturais - Coari 1ªLic : Rosa',
      'PA117 --> Educação Física Tefé 1° Licenciatura : Branco',
      'PA118 --> Ciências Naturais Jutaí 1° Licenciatura : Amarelo',
      'PA119 --> Ciências Naturais Jutaí 2° Licenciatura : Rosa',
      'PA120 --> Ciências Biológicas - Manicoré 1ªLic : Verde',
      'PA121 --> Ciências Biológicas - Envira - 1ª Lic : Azul',
      'PA122 --> Ciências Biológicas - Manicoré - 1ª Lic : Branco',
      'PA123 --> Ciências Biológicas - Maués 1ªLic : Amarelo',
      'PA124 -->  : Verde',
      'PA125 --> Ciências Biológicas - Borba - 1a.Lic : Rosa',
      'PA126 --> Ciências Biológicas - Codajás 1aLic : Azul',
      'PA127 --> Ciências Naturais - Borba 1aLic : Branco',
      'PA128 --> Ciências Naturais - Borba 1aLic : Amarelo',
      'PA129 --> Ciências Biológicas - Caapiranga - 1aLic : Verde',
      'PA130 --> Ciências Naturais - Codajás - 1aLic : Rosa',
      'PA20 --> Letras : ',
      'PA200 --> Matemática Careiro da Várzea 2° Licenciatura : Rosa',
      'PA201 --> Matemática Itacoatiara 2° Licenciatura : Azul',
      'PA202 --> Matemática Autazes 1° Licenciatura : Branco',
      'PA203 --> Química Manaus 2° Licenciatura : Amarelo',
      'PA204 --> Matemática Manacapuru 2° Licenciatura : Rosa',
      'PA205 --> Matemática Coari 1° Licenciatura : Verde',
      'PA206 --> Química São Gabriel da Cachoeira 2° Licenciatura : Azul',
      'PA207 --> Física São Gabriel da Cachoeira 2° Licenciatura : Branco',
      'PA208 --> Química Itacoatiara 2° Licenciatura : Rosa',
      'PA209 --> Matemática Benjamin Constant 1° Licenciatura : Amarelo',
      'PA210 --> Matemática São Paulo de Olivença 1° Licenciatura : Verde',
      'PA211 --> Matemática Tabatinga 1° Licenciatura : Azul',
      'PA212 --> Química Manicoré 2° Licenciatura : Amarelo',
      'PA213 --> Matemática São Gabriel da Cachoeira 1° Licenciatura : Branco',
      'PA214 --> Matemática - Ipixuna 1ªLic : Verde',
      'PA215 --> Matemática - Manaquiri 1ªLic : Azul',
      'PA216 --> Matemática Coari 1° Licenciatura : Rosa',
      'PA217 --> Matemática Envira 1° Licenciatura : Amarelo',
      'PA218 --> Matemática - Maués - 1ª Lic : Rosa',
      'PA219 --> Física - Maués 1ªLic : Amarelo',
      'PA220 --> Física - Novo Airão 1ªLic : Azul',
      'PA221 --> Matemática - Ipixuna 1ªLic : Branco',
      'PA222 -->  : Verde',
      'PA223 -->  : Rosa',
      'PA224 --> Matemática - Caapiranga - 1aLic : Amarelo',
      'PA225 --> Matemática - Codajás - 1aLic : Azul',
      'PA226 --> Matemática - Lábrea - 1aLic : Branco',
      'PA227 --> Matemática - Nova Olinda do Norte - 1aLic : Verde',
      'PA228 -->  : Rosa',
      'PA229 --> Matemática - Sta Isabel do Rio Negro - 1aLic : Amarelo',
      ' -->  : Azul',
      'PA231 --> Matemática - Careiro - 2ª licenciatura : Branco',
      'PA235 --> Matemática - Maraã - 1aLic : Verde',
      'PA236 --> Físcia - Codajás - 1ª licenciatura : Branco',
      'PA237 --> Física - Eirunepé 1aLic : Amarelo',
      'PA239 --> Química - Borba 1aLic : Verde',
      'PA240 --> Química - Maués 1aLic : Azul',
      'PA241 --> Química - Borba 1aLic : Branco',
      'PA242 --> Química - Maués 1aLic : Amarelo',
      'PA300 --> Pedagogia Borba 1° Licenciatura : Azul',
      'PA301 --> Letras Língua e Literatura Inglesa Parintins 2° Licenciatura : Verde',
      'PA302 --> Pedagogia Parintins 1° Licenciatura : Branco',
      'PA303 --> Geografia Manaus 2° Licenciatura : Amarelo',
      'PA304 --> Geografia Itacoatiara 2° Licenciatura : Azul',
      'PA305 --> História Itacoatiara 2° Licenciatura : Amarelo',
      'PA306 --> Letras Língua e Literatura Inglesa Itacoatiara 2° Licenciatura : Rosa',
      'PA307 --> Letras Língua e Literatura Portuguesa Itacoatiara 2° Licenciatura : Verde',
      'PA308 --> Artes  Plásticas Manaus 2° Licenciatura : Branco',
      'PA309 --> Artes Música Parintins 1° Licenciatura : Amarelo',
      'PA310 --> Letras  Língua e Literatura Inglesa Eirunepé 1° Licenciatura  : Rosa',
      'PA311 --> Geografia Manaus 2° Licenciatura : Azul',
      'PA312 --> Pedagogia Manacapuru 1° Licenciatura : Amarelo',
      'PA313 --> Pedagogia Manaus 1° Licenciatura : Rosa',
      'PA314 --> Pedagogia Eirunepé 1° Licenciatura : Branco',
      'PA315 --> História Humaitá 2° Licenciatura : Verde',
      'PA316 --> Letras  Língua e Literatura Inglesa Autazes 1° Licenciatura  : Azul',
      'PA317 -->  : Amarelo',
      'PA318 --> História Eirunepé 2° Licenciatura : Rosa',
      'PA319 --> História Manacapuru 2° Licenciatura : Branco',
      'PA320 --> Pedagogia Manacapuru 1° Licenciatura : Azul',
      'PA324 --> Letras Língua e Literatura Portuguesa Benjamin Constant 2° Licenciatura : Azul',
      'PA325 --> Letras Língua e Literatura Portuguesa Manacapuru 2° Licenciatura : Branco',
      'PA326 --> Letras Língua e Literatura Portuguesa Manaus 2° Licenciatura : Verde',
      'PA327 --> Letras Língua e Literatura Portuguesa Parintins 2° Licenciatura : Rosa',
      'PA328 --> Pedagogia Manaus 1° Licenciatura : Amarelo',
      'PA329 --> Pedagogia Eirunepé 1° Licenciatura : Azul',
      'PA330 --> Pedagogia Humaitá 1° Licenciatura : Branco',
      'PA331 --> Pedagogia Itacoatiara 1° Licenciatura : Verde',
      'PA332 --> Pedagogia Lábrea 1° Licenciatura : Rosa',
      'PA333 --> Pedagogia Parintins 1° Licenciatura : Amarelo',
      'PA334 --> Pedagogia Maués 1° Licenciatura : Azul',
      'PA335 --> Letras Língua e Literatura Portuguesa Autazes 1° Licenciatura : Rosa',
      'PA336 --> Pedagogia Autazes 1° Licenciatura : Branco',
      'PA337 --> Pedagogia Autazes 1° Licenciatura : Verde',
      'PA338 --> Geografia Manacapuru 2° Licenciatura : Rosa',
      'PA339 --> Geografia Manaus 2° Licenciatura : Branco',
      'PA340 --> Letras Língua e Literatura Espanhola São Gabriel da Cachoeira 1° Licenciatura : Amarelo',
      'PA341 --> Pedagogia Eirunepé 1° Licenciatura : Azul',
      'PA342 --> História Manaus 2° Licenciatura : Branco',
      'PA343 --> História Coari 1° Licenciatura : Verde',
      'PA344 --> Letras Língua e Literatura Inglesa Manacapuru 2° Licenciatura : Rosa',
      'PA345 --> Letras Língua e Literatura Inglesa Manaus 1° Licenciatura : Verde',
      'PA346 --> Letras Língua e Literatura Inglesa Manaus 2° Licenciatura : Amarelo',
      'PA347 --> Pedagogia Eirunepé 1° Licenciatura : Azul',
      'PA348 --> Letras Língua e Literatura Portuguesa Parintins 1° Licenciatura : Rosa',
      'PA349 --> Letras Língua e Literatura Portuguesa Coari 1° Licenciatura : Branco',
      'PA350 --> Letras Língua e Literatura Inglesa Iranduba 1° Licenciatura : Rosa',
      'PA351 --> Letras Língua e Literatura Inglesa Coari 1° Licenciatura : Verde',
      'PA352 --> Pedagogia Maués 1° Licenciatura : Rosa',
      'PA353 --> Pedagogia Maués 1° Licenciatura : Amarelo',
      'PA354 --> História São Gabriel da Cachoeira 1° Licenciatura : Branco',
      'PA355 --> Letras Língua e Literatura Inglesa Eirunepé 1° Licenciatura : Verde',
      'PA356 --> História Iranduba 1° Licenciatura : Azul',
      'PA357 --> História Coari 1° Licenciatura : Verde',
      'PA358 --> Letras Língua e Literatura Portuguesa Jutaí 1° Licenciatura : Branco',
      'PA359 --> Geografia São Gabriel da Cachoeira 1° Licenciatura : Rosa',
      'PA360 --> Geografia Eirunepé 2° Licenciatura : Amarelo',
      'PA361 --> Geografia Jutaí 2° Licenciatura : Branco',
      'PA362 --> Geografia Coari 1° Licenciatura : Verde',
      'PA363 --> Geografia Envira 1° Licenciatura : Branco',
      'PA364 --> Pedagogia Benjamin Constant 1° Licenciatura : Azul',
      'PA365 --> Letras Língua e Literatura Portuguesa Benjamin Constant    : Rosa',
      'PA366 --> Pedagogia São Gabriel da Cachoeira 1° Licenciatura : Verde',
      'PA367 --> Pedagogia Eirunepé 1° Licenciatura : Branco',
      'PA368 --> Letras Língua e Literatura Espanhola São Gabriel da Cachoeira 1° Licenciatura : Azul',
      'PA369 --> Letras Língua e Literatura Portuguesa Benjamin Constant 1° Licenciatura : Verde',
      'PA370 --> Letras Língua e Literatura Portuguesa São Paulo de Olivença 1° Licenciatura : Rosa',
      'PA371 -->  : Amarelo',
      'PA372 --> Letras - Língua e Literatura Portuguesa - Codajás 1ªLic : Azul',
      'PA373 --> Letras Língua e Literatura Portuguesa São Gabriel da Cachoeira 1° Licenciatura : Amarelo',
      'PA374 --> Letras Língua e Literatura Portuguesa Eirunepé 1° Licenciatura : Verde',
      'PA375 --> Letras Língua e Literatura Portuguesa Iranduba 1° Licenciatura : Branco',
      'PA376 --> Letras Língua e Literatura Portuguesa Coari 1° Licenciatura : Azul',
      'PA377 --> Letras Língua e Literatura Portuguesa Coari 1° Licenciatura : Rosa',
      'PA378 --> Pedagogia Envira 1° Licenciatura : Verde',
      'PA379 --> Pedagogia Barreirinha 1° Licenciatura : Rosa',
      'PA380 --> Pedagogia Borba 1° Licenciatura : Amarelo',
      'PA381 --> Pedagogia Lábrea 1° Licenciatura : Azul',
      'PA382 --> Letras - Lingua e Literatura Portuguesa - Jurua - 2ªLic : Branco',
      'PA383 --> Letras Língua e Literatura Portuguesa Jutaí 1° Licenciatura : Verde',
      'PA384 --> Letras - Língua e Literatura Portuguesa - Maués 1ªLic : Rosa',
      'PA385 --> Pedagogia Urucurituba 1° Licenciatura : Amarelo',
      'PA386 --> Artes Música Manicoré 1° Licenciatura : Azul',
      'PA387 --> Letras Língua e Literatura Portuguesa Manicoré 1° Licenciatura : Branco',
      'PA388 --> Letras Língua e Literatura Portuguesa Manicoré 1° Licenciatura : Rosa',
      'PA389 --> Letras Língua e Literatura Inglesa Novo Airão 1° Licenciatura : Verde',
      'PA390 --> Pedagogia Novo Airão 1° Licenciatura : Rosa',
      'PA391 --> Sociologia São Gabriel da Cachoeira 1° Licenciatura : Amarelo',
      'PA392 --> Artes Música São Gabriel da Cachoeira 1° Licenciatura : Azul',
      'PA393 --> Artes Plásticas São Gabriel da Cachoeira 1° Licenciatura : Branco',
      'PA394 --> Letras Língua e Literatura Espanhola São Gabriel da Cachoeira 1° Licenciatura : Verde',
      'PA395 --> Pedagogia Urucurituba 1° Licenciatura : Rosa',
      'PA396 --> Sociologia São Gabriel da Cachoeira 1° Licenciatura : Amarelo',
      'PA397 --> Letras Língua e Literatura Inglesa Novo Airão 1° Licenciatura : Azul',
      'PA398 --> Pedagogia Juruá 1° Licenciatura : Branco',
      'PA399 --> Letras - Língua e Literatura Portuguesa - Nova Olinda do Norte - 1ªLic : Verde',
      'PA400 --> Letras Língua e Literatura Inglesa Jutaí 1° Licenciatura : Rosa',
      'PA401 --> História Manicoré 1° Licenciatura : Amarelo',
      'PA402 --> Letras Língua e Literatura Portuguesa Envira 1° Licenciatura : Azul',
      'PA403 --> Letras Língua e Literatura Portuguesa Tefé 2° Licenciatura : Branco',
      'PA404 --> Letras Língua e Literatura Portuguesa Urucará 1° Licenciatura : Verde',
      'PA405 --> Letras - Língua e Literatura Inglesa - Itacoatiara 1ªLic : Rosa',
      'PA406 --> Letras - Língua e Literatura Portuguesa - Nova Olinda do Norte - 1ªLic : Amarelo',
      'PA407 --> Geografia - Coari 1ªLic : Azul',
      'PA408 --> Geografia - Codajás 1ªLic : Branco',
      'PA409 --> Geografia - Maués - 1ª Lic : Verde',
      'PA410 -->  : Rosa',
      'PA411 --> Letras - Língua e Literatura Inglesa - Itacoatiara 1ªLic : Amarelo',
      'PA412 -->  : Azul',
      'PA413 --> Pedagogia - Envira 1ªLic : Branco',
      'PA414 --> Pedagogia - Tefé - 1ªLic : Verde',
      'PA415 --> Artes: Música - Itacoatiara 1ªLic : Rosa',
      'PA416 --> Artes: Música - Novo Airão 1ªLic : Amarelo',
      'PA417 --> Artes: Música - Itacoatiara 1ªLic : Azul',
      'PA418 --> Artes Visuais - Manicoré - 1aLic : Branco',
      'PA419 --> Artes Visuais - Benjamin Constant 1aLic : Verde',
      'PA420 --> Artes Visuais - Envira 1aLic : Rosa',
      'SB02 --> Biotecnologia : Amarelo',
      'SE01 --> Matematica - Parintins : ',
      'SE02 --> Matematica - Coari : ',
      'SE03 --> Matematica - Manacapuru : ',
      'SE04 --> Matematica - Itacoatiara : ',
      'SE05 --> Historia - Itacoatiara : ',
      'SE06 --> Lic. Geografia - Humaita : ',
      'SE07 --> Lic. Geografia - Manacapuru : ',
      'SE08 --> Lic. Geografia - Itacoatiara : ',
      'SE09 --> Ciencias - Parintins : ',
      'SE10 --> Ciencias - Coari : ',
      'SE11 --> Ciencias - Benjamin Constant : ',
      'SE12 --> Ciências - Itacoatiara : Azul',
      'SE13 --> Ciências - Manacapuru : Branco',
      'SE14 --> Matematica Matutino 1 : ',
      'SE15 --> Matematica Matutino 2 : ',
      'SE16 --> Matematica Vespertino : ',
      'SE17 --> Matematica Noturno 1 : ',
      'SE18 --> Ciências (Plenificação) SEDUC : Verde',
      'SE19 --> Ciências (Plenificação) SEDUC : Rosa',
      'SE20 --> Ciências (Plenificação) SEDUC : Amarelo',
      'SE21 --> Ciências (Plenificação) SEDUC : Azul',
      'SE22 --> Educação Física Plenificação Manaus : ',
      'SE23 --> Educação Física Plenificação Manaus : ',
      'SE24 --> Plenificação em Letras : Branco',
      'SE25 --> Matematica Eirunepe : ',
      'SE26 --> Lic. Historia Manaus : ',
      'SE27 --> Lic. Historia Manaus : ',
      'SE28 --> Lic. Geografia Manaus : ',
      'SE29 --> Lic. Geografia Manaus : ',
      'SE30 --> Letras Vespertino : ',
      'SE31 --> Lic. Historia Eirunepe : ',
      'SE32 --> Licenciatura em História - Parintins : Verde',
      'SE33 --> Letras Noturno : ',
      'SE34 --> Licenciatura em Geografia - Benj. Constant : Rosa',
      'SE35 --> Letras Eirunepe : ',
      'SE36 --> Letras Labrea : ',
      'SE37 --> Letras - Manicoré : Amarelo',
      'SE38 --> Letras Parintins : ',
      'SE39 --> Letras - Manaus : Azul',
      'SE40 --> Letras Manaus : ',
      'SE41 --> Letras Cont. Mat. Manaus : ',
      'SE42 --> Letras - Contínuo Not. Manaus : Branco',
      'SE43 --> Letras Diurno Manaus : ',
      'SE44 --> Matemática - Eirunepé : Verde',
      'SE45 --> Matemática - Humaitá : Rosa',
      'SE46 --> Matemática - Barcelos : Amarelo',
      'SE47 --> Matemática - Lábrea : Azul',
      'SE48 --> Matemática - Modular Semestral - Licenc. em Matemática/Manaus-Recesso : Branco',
      'SE49 --> Matematica Noturno 2 : ',
      'SE50 --> Matemática - Vespertino Licenc. em Matemática/Manaus : Verde',
      'SE51 --> Ciencias Lic. Noturno : ',
      'SE52 --> Ciencias Lic. Noturno : ',
      'SE53 --> Ciências - Licenciatura : Rosa',
      'SE54 --> Ciências - Lábrea : Amarelo',
      'SE55 --> Ciências - Barcelos : Azul',
      'SE56 --> Ciências - Humaitá : Branco',
      'SE57 --> Ciências - Eirunepé : Verde',
      'SE59 --> Licenciatura em História - Lábrea : Rosa',
      'SE60 --> Licenciatura em História - Tabatinga : Amarelo',
      'SE65 --> Plenificação em História : Azul',
      'SE66 --> Plenificação em História : Branco',
      'SE68 --> Letras - Parintins : Verde',
      'SE69 --> História - Manaus : Rosa',
      'SE70 --> Matematica Noturno : ',
      'SE71 --> Letras Vespertino : ',
      'SE72 --> Geografia Manaus : ',
      'SE73 --> Plenificação Geografia Manaus : ',
      'SE74 --> Plenificação Geografia Manaus : ',
      'SE76 --> Plenificação Letras : ',
      'SE78 --> Plenificação em Matemática - Licenciatura em Matemática-Manaus : Amarelo',
      'SE82 --> Licen. em Educação Física - Manacapuru : Azul',
      'SG01 --> Filosofia Lic. S.G.Cachoeira : ',
      'SG02 --> Ciências Sociais - S G da Cachoeira - Licenciatura em Ciëncias Sociais : Branco',
      'SG03 --> Geografia - Licenciatura - S G da Cachoeira : Verde',
      'SG04 --> Matemática - S G da Cachoeira - Licenciatura em Matemática : Rosa',
      'SG05 --> Letras - São Gabriel da Cachoeira - Língua Portuguesa : Amarelo',
      'SH01 --> Desenvolvimento Municipal : Azul',
      'SH02 --> Administração Universitária : Branco',
      'SH03 --> Formação em Gestão de Desenvolvimento Regional : Verde',
      'SH04 --> Formação em Gestão de Desenvolvimento Regional : Rosa',
      'SH05 --> Curso Seq.Form.Esp. Expr. Visual - Parintins : Amarelo',
      'SH06 --> Formação em Gestão de Desenvolvimento Regional : Azul',
      'SI01 --> Ciencias Itacoatiara : ',
      'SI02 --> Matematica Itacoatiara : ',
      'SI03 --> Lic. Historia Itacoatiara : ',
      'SI04 --> Lic. Geografia Itacoatiara : ',
      'SI05 --> Pedagogia - Urucará : Branco',
      'SI06 --> Matematica Novo Airao : ',
      'SI07 --> Ciências - Novo Airão : Verde',
      'SI10 --> Matematica Borba : ',
      'SI11 --> Pedagogia - Borba : ',
      'SI12 --> Matemática - Iranduba : Rosa',
      'SI13 --> Pedagogia - Iranduba : ',
      'SI14 --> Pedagogia - Presid. Figueiredo : ',
      'SI17 --> Pedagogia - Benjamin Constant : ',
      'SI19 --> Pedagogia - Manacapuru : ',
      'SI20 --> Pedagogia - Envira : ',
      'SI21 --> Pedagogia - Carauari : ',
      'SI22 --> Matematica - Maues : ',
      'SI23 --> Pedagogia - Manacapuru : ',
      'SI24 --> Pedagogia - Eirunepe : ',
      'SI25 --> Pedagogia - Tabatinga : ',
      'SI26 --> Pedagogia - Urucará : ',
      'SI27 --> Pedagogia - Lábrea : ',
      'SI28 --> Pedagogia - Coari : ',
      'SI29 --> Pedagogia - Humaita : ',
      'SI30 --> Educação Física - Manacapuru : Amarelo',
      'SI31 --> Ciências - Parintins : Azul',
      'SI32 --> Licenciatura em História - Careiro Várzea : Branco',
      'SI33 --> Pedagogia - Lábrea : Verde',
      'SI34 --> Pedagogia - São Gabriel da Cachoeira : Rosa',
      'SI35 --> Pedagogia - Lábrea : Amarelo',
      'SI36 --> Pedagogia - Maués : Azul',
      'SI37 --> Pedagogia - Maués : Branco',
      'SI38 --> Pedagogia - Maués : Verde',
      'SI39 --> Pedagogia - Maués : Rosa',
      'SI40 --> Pedagogia - Maués : Amarelo',
      'SI41 --> Artes Plásticas/Parintins : Azul',
      'SI43 --> Pedagogia - Benjamin Constant : Branco',
      'SI44 --> Matemática - Benjamin Constant : Verde',
      'SI45 --> Pedagogia - Magist. 1ª a 4ª série/Guajará : Rosa',
      'SI46 --> Pedagogia - Pauini : Amarelo',
      'SI47 --> Ciências Naturais - Licenciatura/Maués : Azul',
      'SI48 --> Pedagogia - Pauini : Branco',
      'SI49 --> Pedagogia - Benjamin Constant : Verde',
      'SI50 --> Licenciatura em Ciências Agrárias : Rosa',
      'SI51 --> Pedagogia - Coari : Amarelo',
      'SI52 --> Pedagogia - Coari : Azul',
      'SI53 --> Pedagogia - Manicoré : Branco',
      'SM01 --> Pedagogia Matutino Manaus : ',
      'SM02 --> Pedagogia Vespertino Manaus : ',
      'SM03 --> Pedagogia Vespertino Manaus : ',
      'SM04 --> Pedagogia Noturno - Manaus : Verde',
      'SM05 --> Pedagogia Noturno - Manaus : Rosa',
      'SM06 --> Pedagogia Noturno - Manaus : ',
      'SM07 --> Pedagogia Noturno - Manaus : ',
      'SM08 --> Pedagogia Noturno - Manaus : ',
      'SM09 --> Pedagogia Noturno - Manaus : Amarelo',
      'SM10 --> Pedagogia Mod. Sem. - Manaus : Azul',
      'SM11 --> Letras Mod.Not.Cont. Manaus : ',
      'SM12 --> Letras Manaus Mod.Sem. : ',
      'SM13 --> Matematica Matutino : ',
      'SM14 --> Matematica Noturno : ',
      'SM15 --> Lic. Historia Manaus : ',
      'SM16 --> Licenciatura em História - Manaus : Branco',
      'SM17 --> Lic. Geografia Manaus : ',
      'SM18 --> Licenciatura em Geografia - Manaus : Verde',
      'SM19 --> Ciências - Licenciatura/Noturno : Rosa',
      'SM20 --> Ciências - Licenciatura : Amarelo',
      'SM21 --> Matematica Modular Semestral : ',
      'SM22 --> Pedagogia Modular Semestral Manaus : ',
      'SM23 --> Pedagogia Mod. Sem. - Manaus : Azul',
      'SM24 --> Pedagogia Matutino Manaus : ',
      'SM25 --> Pedagogia Vespertino Manaus : ',
      'SM26 --> Pedagogia Vespertino Manaus : ',
      'SM27 --> Pedagogia Noturno - Manaus : ',
      'SM28 --> Pedagogia Noturno - Manaus : ',
      'SM29 --> Pedagogia Noturno - Manaus : ',
      'SM30 --> Pedagogia Noturno - Manaus : ',
      'SM31 --> Pedagogia Noturno - Manaus : ',
      'SM32 --> Pedagogia Noturno - Manaus : Branco',
      'SM33 --> Pedagogia Noturno - Manaus : Verde',
      'SM34 --> Pedagogia Mod. Manaus : Rosa',
      'SM35 --> Pedagogia Mod. Manaus : Amarelo',
      'SM36 --> Pedagogia Matutino : Azul',
      'SM37 --> Pedagogia Noturno - Manaus : Branco',
      'SM38 --> Pedagogia Noturno - Manaus : Verde',
      'SM39 --> Pedagogia : Rosa',
      'SM40 --> Pedagogia : Amarelo',
      'SM41 --> Pedagogia : Azul',
      'SM42 --> Pedagogia : Branco',
      'SM43 --> Educação Física : Verde',
      'SM44 --> Formação de Professores Indígenas : Rosa',
      'SM44-EB --> Formação de Professores Indígenas - Exatas e Biológicas : Rosa',
      'SM44-HS --> Formação de Professores Indígenas - Humanas e Sociais : Rosa',
      'SM44-LA --> Formação de Professores Indígenas - Letras e Artes : Rosa'
    ];

    $( "#tags" ).autocomplete({
      source: cores
    });
  } );
  </script>
</head>
<body>
  <div id="logoufam" >

  <label for="chec">
  <img width="100px" height="90px" src="ufam.png"/>
  </label>
  <label id="insti">Universidade Federal do Amazonas<br>
  Pró-Reitoria de Ensino de Graduação<br>
  Departamento de Registro Acadêmico<br>
  Arquivo Acadêmico<br>

  </label>
  </div>
  <div>
  <input type="checkbox" id="chec">
  <nav id="nave" >
      <ul>
        <li><a href="tela_inicial.php">Inicio</a></li>
      <li><a href="altera_tema.php">Alterar tema</a></li>
      <li><a href="sair.php">Sair</a></li>
      </ul>
  </nav>
  </div>



<div class="cor_etq_claaa">
  <label for="tags">Qual o curso?: </label>
  <input id="tags">
</div>


</body>
</html>
